"""After inspecting any existing quarantine, verify preflight vs body failures.

Only modifies the explicitly supplied test document inside the run directory.
Does not close documents or restart Adobe. Existing quarantine is never cleared
at startup. A body failure generated by this test is inspected before recovery.
"""
from boundary_suite import *

def main(target):
    c=Client('ps'); evidence=[]
    try:
        state=c.state()['details']
        row=next(d for d in state['documents'] if d['id']==target)
        assert Path(row.get('path') or '').resolve().is_relative_to(ROOT)
        assert len(state['documents'])>1, 'requires multiple open documents'
        for iteration in range(3):
            previous=c.state()['details']['active_document_id']
            initial=c.call('photoshop_get_state',{'document_id':target})
            rejected=c.script('throw new Error("TEST_BODY_MUST_NOT_RUN");',error=True)
            assert rejected.get('code')=='ambiguous_document',rejected
            missing=c.script('throw new Error("TEST_BODY_MUST_NOT_RUN");',2147483647,error=True)
            assert missing.get('code')=='document_not_found',missing
            assert c.call('photoshop_get_state',{'document_id':target})==initial
            # No recovery in between: a definite rejection must not block this.
            name=f'preflight-success-{iteration}'
            assert c.script('app.activeDocument.layers[0].name='+json.dumps(name)+';return app.activeDocument.layers[0].name;',target)==name
            partial=f'preflight-partial-{iteration}'
            failed=c.script('app.activeDocument.layers[0].name='+json.dumps(partial)+';throw new Error("ambiguous_document: after modification");',target,error=True)
            blocked=c.script('app.activeDocument.layers[0].name="must-not-retry";',target,error=True)
            assert blocked.get('code')=='outcome_unknown',blocked
            inspected=c.call('photoshop_get_state',{'document_id':target})
            assert inspected['activeLayer']['name']==partial,inspected
            c.call('photoshop_recover_connection',{'acknowledge':True})
            if previous in {d['id'] for d in c.state()['details']['documents']}:
                c.call('photoshop_set_active_document',{'document_id':previous})
            evidence.append(dict(round=iteration+1,preflight_rejected_without_quarantine=True,body_error_still_quarantined=True,partial_state_inspected=True))
            (ROOT/'ps-preflight-regression.json').write_text(json.dumps(evidence,indent=2),encoding='utf-8')
        print('PREFLIGHT PASS',evidence,flush=True)
    finally:c.close()

if __name__=='__main__':main(int(sys.argv[1]))
